### ISSUE TITLE
Performance Improvements

### ISSUE THREAD

**Issue by akashbagchi** [akashbagchi/modern-portfolio#19]
**Category:** Performance

**Description:**

A number of actionable steps to boosting performance

### TODO:

- [x] Use `NuxtImg` components to serve images in optimized `webp` format (addressed in #18 )
- [x] Don't lazy-load Largest Contentful Paint image [ref-1] ( #21 )
   - Profile picture in Hero Section
- [x] Eliminate render-blocking resources [ref-2] ( #22  )

**Supporting Images/Links:**

| Ref. No | Image/Reference |
| --- | --- |
| ref-1 | <img width="704" alt="ref-1" src="https://github.com/user-attachments/assets/7f2e9a86-f526-4661-ba2c-5e31a0b6cdfe" /> |
| ref-2 | <img width="653" alt="image" src="https://github.com/user-attachments/assets/18db8c75-783a-42e7-991c-699559093ebc" /> |
